modules_dir = "artifacts/"

[[module]]
    name = "ipfs_effector"
    mem_pages_count = 100
    logger_enabled = true

    [module.mounted_binaries]
    ipfs = "/usr/local/bin/ipfs"

    [module.wasi]
    envs = { "IPFS_ADDR" = "/dns4/relay02.fluence.dev/tcp/15001", "timeout" = "1s" }

[[module]]
    name = "ipfs_pure"
    mem_pages_count = 100
    logger_enabled = true
