modules_dir = "artifacts/"

[[module]]
    name = "ipfs_effector"
    mem_pages_count = 100
    logger_enabled = true

    [module.mounted_binaries]
    ipfs = "/opt/homebrew/bin/ipfs"

    [module.wasi]
    envs = { "/tmp/vault" = "/tmp" }

[[module]]
    name = "ipfs_pure"
    mem_pages_count = 100
    logger_enabled = true
