name: "publish-release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Publish"
    runs-on: ubuntu-latest
    container: rust
    defaults:
      run:
        working-directory: .
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download jq
        run: |
          curl -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -o /usr/local/bin/jq
          chmod +x /usr/local/bin/jq

      - name: Download marine
        run: bash $GITHUB_WORKSPACE/.github/download_marine.sh

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        run: |
          rustup toolchain install nightly-2021-04-24-x86_64-unknown-linux-gnu
          rustup default nightly-2021-04-24-x86_64-unknown-linux-gnu
          rustup target add wasm32-wasi --toolchain nightly-2021-04-24-x86_64-unknown-linux-gnu

      - name: Build ipfs-adapter
        working-directory: .
        run: ./build.sh

      - name: Create distribution package
        working-directory: .
        run: |
          tar -zcvf ipfs-adapter.tar.gz artifacts/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ipfs-adapter ${{ GITHUB_REF#refs/tags/ }}
          tag_name: ${{ GITHUB_REF#refs/tags/ }}
          files: |
            ipfs-adapter.tar.gz
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}