name: Run tests

on:
  pull_request:
    paths-ignore:
      - "**.md"

  push:
    branches:
      - "master"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    name: "cargo nextest"
    runs-on: builder

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup marine
        uses: fluencelabs/setup-marine@v1

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v2.0.0
        with:
          crate: cargo-nextest

      - name: Build aqua-ipfs
        working-directory: ./service
        run: ./build.sh

      - name: Run cargo nextest
        working-directory: ./service
        env:
          NEXTEST_TEST_THREADS: 10
        run: cargo nextest run --release --all-features --no-fail-fast

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -Z unstable-options --all --manifest-path service/Cargo.toml


  lints:
    name: Lints
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path service/Cargo.toml -- --check
